namespace: kn6plv
name: aredn
version: 0.0.12
readme: README.md
authors:
  - Tim Wilkinson KN6PLV <tim.j.wilkinson@gmail.com>
description: AREDN node configuration
license:
  - GPL-2.0-or-later
tags: []
dependencies:
repository: https://github.com/kn6plv/ansible4aredn
documentation: https://arednmesh.readthedocs.io
homepage: https://www.arednmesh.org
issues: https://github.com/kn6plv/ansible4aredn/issues
build_ignore:
  - "*.tar.gz"
